# permissions for end users to edit newcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: newcronjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: newcronjob-controller
    app.kubernetes.io/part-of: newcronjob-controller
    app.kubernetes.io/managed-by: kustomize
  name: newcronjob-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - newcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - newcronjobs/status
  verbs:
  - get
