---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - newcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - newcronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - newcronjobs/status
  verbs:
  - get
  - patch
  - update
